# Generated by Django 4.2 on 2023-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_1', models.CharField(blank=True, max_length=100, null=True)),
                ('step_1_int', models.IntegerField(blank=True, null=True)),
                ('step_1_unit', models.CharField(blank=True, choices=[('miles', 'Miles'), ('reps', 'Reps'), ('lbs', 'Lbs'), ('minute', 'Minutes')], max_length=10, null=True)),
                ('is_step_1_complete', models.BooleanField(default=False)),
                ('step_2', models.CharField(blank=True, max_length=100, null=True)),
                ('step_2_int', models.IntegerField(blank=True, null=True)),
                ('step_2_unit', models.CharField(blank=True, choices=[('miles', 'Miles'), ('reps', 'Reps'), ('lbs', 'Lbs'), ('minute', 'Minutes')], max_length=10, null=True)),
                ('is_step_2_complete', models.BooleanField(default=False)),
                ('step_3', models.CharField(blank=True, max_length=100, null=True)),
                ('step_3_int', models.IntegerField(blank=True, null=True)),
                ('step_3_unit', models.CharField(blank=True, choices=[('miles', 'Miles'), ('reps', 'Reps'), ('lbs', 'Lbs'), ('minute', 'Minutes')], max_length=10, null=True)),
                ('is_step_3_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
